"""
Reusable visualisation functions for wavelet-ICA / PCA decomposition.

These plots reproduce, in script form, the figures generated by the four
exploratory notebooks under ``notebooks/04-wavelet-ica-analysis/``.

Every public function:
- accepts pre-computed numpy arrays and display parameters,
- writes one figure to disk via an optional ``save_path``,
- does **not** call ``plt.show()`` — the caller decides,
- returns the created :class:`~matplotlib.figure.Figure`.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.figure import Figure

_logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _save_fig(fig: Figure, save_path: Optional[Path]) -> None:
    if save_path is None:
        return
    save_path = Path(save_path)
    save_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(save_path, dpi=150, bbox_inches="tight")


def _ensure_axes_iterable(axes):
    """Return *axes* as a flat list even when matplotlib gave a scalar."""
    if hasattr(axes, "__iter__"):
        return list(axes)
    return [axes]


_BAND_COLORS: dict[str, str] = {
    "delta": "#d4e6f1",
    "theta": "#d5f5e3",
    "alpha": "#fdebd0",
    "beta": "#fadbd8",
    "gamma": "#e8daef",
}


# ===================================================================
# Super-Brain plots (12)
# ===================================================================


def plot_superbrain_pca_scree(
    explained_variance_ratio: np.ndarray,
    *,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """PCA scree plot (bar) + cumulative variance (line).

    :param explained_variance_ratio: ``(n_pca,)`` variance ratios.
    """
    n = len(explained_variance_ratio)
    cumvar = np.cumsum(explained_variance_ratio)

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    axes[0].bar(range(1, n + 1), explained_variance_ratio, color="steelblue")
    axes[0].set_xlabel("Component")
    axes[0].set_ylabel("Variance explained")
    axes[0].set_title(f"PCA Scree Plot — {label}")

    axes[1].plot(range(1, n + 1), cumvar, "o-", color="steelblue")
    axes[1].axhline(0.9, ls="--", color="gray", label="90 %")
    axes[1].set_xlabel("Number of components")
    axes[1].set_ylabel("Cumulative variance explained")
    axes[1].set_title(f"Cumulative Variance — {label}")
    axes[1].legend()

    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_superbrain_pca_timecourses(
    scores: np.ndarray,
    sfreq: float,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """PCA component time courses.

    :param scores: ``(T, n_pca)`` PCA scores.
    :param sfreq: Sampling frequency (Hz).
    """
    n_show = min(n_show, scores.shape[1])
    time = np.arange(scores.shape[0]) / sfreq

    fig, axes = plt.subplots(n_show, 1, figsize=(14, 2.5 * n_show), sharex=True)
    axes = _ensure_axes_iterable(axes)
    for i, ax in enumerate(axes):
        ax.plot(time, scores[:, i], lw=0.8, color="steelblue")
        ax.set_ylabel(f"PC {i + 1}")
    axes[-1].set_xlabel("Time (s)")
    fig.suptitle(f"PCA Component Time Courses — {label}", fontsize=13)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_superbrain_pca_subject_loadings(
    loadings_4d: np.ndarray,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Horizontal bar chart of per-subject mean |loading|.

    :param loadings_4d: ``(n_pca, S, C, F)`` reshaped PCA components.
    """
    # subject loadings: mean over channels and freqs
    subj_load = np.abs(loadings_4d).mean(axis=(2, 3))  # (K, S)
    n_show = min(n_show, subj_load.shape[0])
    n_subj = subj_load.shape[1]

    fig, axes = plt.subplots(1, n_show, figsize=(3 * n_show, 4), sharey=True)
    axes = _ensure_axes_iterable(axes)
    for i, ax in enumerate(axes):
        ax.barh(range(n_subj), subj_load[i], color="steelblue")
        ax.set_xlabel("|loading|")
        ax.set_title(f"PC {i + 1}")
    axes[0].set_yticks(range(n_subj))
    axes[0].set_yticklabels([f"S{s + 1}" for s in range(n_subj)])
    axes[0].set_ylabel("Subject")
    fig.suptitle(f"Subject Loadings — {label}", fontsize=13)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_superbrain_pca_channel_topomap(
    loadings_4d: np.ndarray,
    info,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Optional[Figure]:
    """Scalp topomaps of PCA channel loadings (mean |loading| over S, F).

    :param loadings_4d: ``(n_pca, S, C, F)``.
    :param info: MNE Info object.
    """
    if info is None:
        _logger.warning("[%s] No MNE Info; skipping topomap.", label)
        return None

    import mne
    from mne.viz import plot_topomap

    eeg_info = mne.pick_info(info, mne.pick_types(info, eeg=True))
    ch_load = np.abs(loadings_4d).mean(axis=(1, 3))  # (K, C)
    n_show = min(n_show, ch_load.shape[0])

    fig, axes = plt.subplots(1, n_show, figsize=(3.5 * n_show, 4))
    axes = _ensure_axes_iterable(axes)
    last_im = None
    for i, ax in enumerate(axes):
        vals = ch_load[i]
        if vals.shape[0] < len(eeg_info["ch_names"]):
            topo_info = mne.pick_info(eeg_info, list(range(vals.shape[0])))
        else:
            topo_info = eeg_info
        vlim = np.percentile(vals, 99)
        last_im, _ = plot_topomap(
            vals, topo_info, axes=ax, show=False, cmap="RdBu_r", vlim=(0, vlim)
        )
        ax.set_title(f"PC {i + 1}")
    fig.suptitle(f"Channel Loadings (topomap) — {label}", fontsize=12)
    if last_im is not None:
        fig.colorbar(last_im, ax=axes[-1], label="mean |loading|")
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_superbrain_pca_freq_loadings(
    loadings_4d: np.ndarray,
    freqs: np.ndarray,
    *,
    bands: Optional[dict[str, tuple[float, float]]] = None,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Per-component frequency loading curves with band shading.

    :param loadings_4d: ``(n_pca, S, C, F)``.
    :param freqs: Morlet frequencies (Hz).
    """
    freq_load = np.abs(loadings_4d).mean(axis=(1, 2))  # (K, F)
    n_show = min(n_show, freq_load.shape[0])

    fig, axes = plt.subplots(n_show, 1, figsize=(10, 2.5 * n_show), sharex=True)
    axes = _ensure_axes_iterable(axes)
    for i, ax in enumerate(axes):
        ax.plot(freqs, freq_load[i], color="steelblue", lw=1.5)
        ax.set_ylabel("|loading|")
        ax.set_title(f"PC {i + 1}")
        if bands is not None:
            for band, (lo, hi) in bands.items():
                ax.axvspan(lo, hi, alpha=0.2, color=_BAND_COLORS.get(band, "grey"))
    axes[-1].set_xlabel("Frequency (Hz)")
    fig.suptitle(f"Frequency Loadings — {label}", fontsize=13)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_superbrain_pca_spectrograms(
    scores: np.ndarray,
    sfreq: float,
    freqs_max: float,
    *,
    n_show: int = 4,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """STFT spectrograms of PCA component time courses.

    :param scores: ``(T, n_pca)``.
    :param sfreq: Sampling frequency (Hz).
    :param freqs_max: Maximum frequency to display (Hz).
    """
    from scipy.signal import spectrogram as sp_spectrogram

    n_show = min(n_show, scores.shape[1])
    nperseg = int(sfreq * 2)
    noverlap = int(sfreq)

    fig, axes = plt.subplots(n_show, 1, figsize=(14, 3 * n_show), sharex=True)
    axes = _ensure_axes_iterable(axes)
    for i, ax in enumerate(axes):
        f, t, Sxx = sp_spectrogram(
            scores[:, i], fs=sfreq, nperseg=nperseg, noverlap=noverlap
        )
        mask = f <= freqs_max
        Sxx_db = 10 * np.log10(Sxx[mask] + 1e-12)
        ax.pcolormesh(t, f[mask], Sxx_db, cmap="inferno", shading="auto")
        ax.set_ylabel("Freq (Hz)")
        ax.set_title(f"PC {i + 1} spectrogram")
    axes[-1].set_xlabel("Time (s)")
    fig.suptitle(f"Component Spectrograms — {label}", fontsize=13)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_superbrain_pca_component_isc(
    mean_loo_isc: np.ndarray,
    *,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Bar chart of mean LOO-ISC per PCA component.

    :param mean_loo_isc: ``(K,)`` mean LOO-ISC per component.
    """
    n = len(mean_loo_isc)
    fig, ax = plt.subplots(figsize=(max(8, n * 0.6), 5))
    colors = ["steelblue" if v >= 0 else "salmon" for v in mean_loo_isc]
    ax.bar(range(1, n + 1), mean_loo_isc, color=colors)
    ax.axhline(0, ls="--", color="gray", lw=0.8)
    ax.set_xlabel("Component")
    ax.set_ylabel("Mean LOO-ISC")
    ax.set_title(f"ISC of PCA Component Time Courses — {label}")
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_superbrain_cross_component_correlation(
    pca_scores: np.ndarray,
    ica_sources: np.ndarray,
    *,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Cross-component correlation matrices for PCA and ICA.

    :param pca_scores: ``(T, n_pca)``.
    :param ica_sources: ``(T, n_ica)``.
    """
    pca_corr = np.corrcoef(pca_scores.T)
    ica_corr = np.corrcoef(ica_sources.T)

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    for ax, corr, title in [
        (axes[0], pca_corr, "PCA score correlations"),
        (axes[1], ica_corr, "ICA score correlations"),
    ]:
        im = ax.imshow(corr, cmap="RdBu_r", vmin=-1, vmax=1)
        ax.set_xlabel("Component")
        ax.set_ylabel("Component")
        ax.set_title(title)
        fig.colorbar(im, ax=ax, label="Pearson r")
    fig.suptitle(f"Cross-Component Correlations — {label}", fontsize=13)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_superbrain_ica_timecourses(
    ica_sources: np.ndarray,
    sfreq: float,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """ICA independent component time courses.

    :param ica_sources: ``(T, n_ica)``.
    :param sfreq: Sampling frequency (Hz).
    """
    n_show = min(n_show, ica_sources.shape[1])
    time = np.arange(ica_sources.shape[0]) / sfreq
    vlim = np.percentile(np.abs(ica_sources[:, :n_show]), 99)

    fig, axes = plt.subplots(n_show, 1, figsize=(14, 2.5 * n_show), sharex=True)
    axes = _ensure_axes_iterable(axes)
    for i, ax in enumerate(axes):
        ax.plot(time, ica_sources[:, i], lw=0.8, color="darkorange")
        ax.set_ylim(-vlim, vlim)
        ax.axhline(0, ls="--", color="gray", lw=0.5)
        ax.set_ylabel(f"IC {i + 1}")
    axes[-1].set_xlabel("Time (s)")
    fig.suptitle(f"ICA Component Time Courses — {label}", fontsize=13)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_superbrain_ica_topomap_mean(
    ica_ch_mean: np.ndarray,
    info,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Optional[Figure]:
    """Topomaps of mean ICA channel loading across subjects.

    :param ica_ch_mean: ``(C, n_ica)`` mean channel loadings.
    :param info: MNE Info.
    """
    if info is None:
        _logger.warning("[%s] No MNE Info; skipping topomap.", label)
        return None

    import mne
    from mne.viz import plot_topomap

    eeg_info = mne.pick_info(info, mne.pick_types(info, eeg=True))
    n_show = min(n_show, ica_ch_mean.shape[1])

    fig, axes = plt.subplots(1, n_show, figsize=(3.5 * n_show, 4))
    axes = _ensure_axes_iterable(axes)
    last_im = None
    for i, ax in enumerate(axes):
        vals = ica_ch_mean[:, i]
        if vals.shape[0] < len(eeg_info["ch_names"]):
            topo_info = mne.pick_info(eeg_info, list(range(vals.shape[0])))
        else:
            topo_info = eeg_info
        vlim = np.percentile(np.abs(vals), 99)
        last_im, _ = plot_topomap(
            vals, topo_info, axes=ax, show=False, cmap="RdBu_r", vlim=(-vlim, vlim)
        )
        ax.set_title(f"IC {i + 1}")
    fig.suptitle(f"ICA Topomaps — Mean Loading Across Subjects — {label}", fontsize=12)
    if last_im is not None:
        fig.colorbar(last_im, ax=axes[-1], label="mean loading")
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_superbrain_ica_topomap_variance(
    ica_ch_var: np.ndarray,
    info,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Optional[Figure]:
    """Topomaps of ICA channel loading variance across subjects.

    :param ica_ch_var: ``(C, n_ica)`` variance of channel loadings.
    :param info: MNE Info.
    """
    if info is None:
        _logger.warning("[%s] No MNE Info; skipping topomap.", label)
        return None

    import mne
    from mne.viz import plot_topomap

    eeg_info = mne.pick_info(info, mne.pick_types(info, eeg=True))
    n_show = min(n_show, ica_ch_var.shape[1])

    fig, axes = plt.subplots(1, n_show, figsize=(3.5 * n_show, 4))
    axes = _ensure_axes_iterable(axes)
    last_im = None
    for i, ax in enumerate(axes):
        vals = ica_ch_var[:, i]
        if vals.shape[0] < len(eeg_info["ch_names"]):
            topo_info = mne.pick_info(eeg_info, list(range(vals.shape[0])))
        else:
            topo_info = eeg_info
        vmax = np.percentile(vals, 99)
        last_im, _ = plot_topomap(
            vals, topo_info, axes=ax, show=False, cmap="YlOrRd", vlim=(0, vmax)
        )
        ax.set_title(f"IC {i + 1}")
    fig.suptitle(f"ICA Topomaps — Variance Across Subjects — {label}", fontsize=12)
    if last_im is not None:
        fig.colorbar(last_im, ax=axes[-1], label="variance of loading")
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_superbrain_ica_interindividual_correlation(
    ica_channel_loadings: np.ndarray,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Inter-individual correlation matrices of ICA channel loadings.

    :param ica_channel_loadings: ``(S, C, n_ica)`` per-subject channel loadings.
    """
    n_ica = ica_channel_loadings.shape[2]
    n_show = min(n_show, n_ica)
    n_subj = ica_channel_loadings.shape[0]

    fig, axes = plt.subplots(
        1, n_show, figsize=(3.5 * n_show, 3.5), constrained_layout=True
    )
    axes = _ensure_axes_iterable(axes)
    last_im = None
    for i, ax in enumerate(axes):
        corr = np.corrcoef(ica_channel_loadings[:, :, i])
        last_im = ax.imshow(corr, cmap="RdBu_r", vmin=-1, vmax=1)
        ax.set_xticks(range(n_subj))
        ax.set_xticklabels([f"S{s + 1}" for s in range(n_subj)], fontsize=7)
        ax.set_yticks(range(n_subj))
        ax.set_yticklabels([f"S{s + 1}" for s in range(n_subj)], fontsize=7)
        ax.set_title(f"IC {i + 1}")
    if last_im is not None:
        fig.colorbar(last_im, ax=axes[-1], label="Pearson r")
    fig.suptitle(
        f"Inter-Individual IC Correlations (channel loadings) — {label}",
        fontsize=12,
    )
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


# ===================================================================
# Inter-Subject plots (12)
# ===================================================================


def plot_intersubject_pca_scree(
    explained_variance_ratio: np.ndarray,
    *,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """PCA scree plot for the inter-subject approach."""
    return plot_superbrain_pca_scree(
        explained_variance_ratio, label=label, save_path=save_path
    )


def plot_intersubject_pca_channel_freq_maps(
    components_2d: np.ndarray,
    freqs: np.ndarray,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Spatial-spectral component maps (channel × frequency heatmaps).

    :param components_2d: ``(n_pca, C, F)`` PCA components reshaped.
    :param freqs: Morlet frequencies (Hz).
    """
    n_show = min(n_show, components_2d.shape[0])
    n_cols = min(3, n_show)
    n_rows = int(np.ceil(n_show / n_cols))

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(5 * n_cols, 4 * n_rows))
    flat = np.array(axes).flatten() if n_show > 1 else [axes]
    for i in range(n_show):
        ax = flat[i]
        im = ax.imshow(
            components_2d[i],
            aspect="auto",
            origin="lower",
            extent=[freqs[0], freqs[-1], 0, components_2d.shape[1]],
            cmap="RdBu_r",
        )
        ax.set_xlabel("Frequency (Hz)")
        ax.set_ylabel("Channel index")
        ax.set_title(f"PC {i + 1}")
        fig.colorbar(im, ax=ax)
    for i in range(n_show, len(flat)):
        flat[i].set_visible(False)
    fig.suptitle(f"Spatial-Spectral Component Maps — {label}", fontsize=13)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_intersubject_pca_subject_activations(
    scores_3d: np.ndarray,
    sfreq: float,
    *,
    n_show: int = 4,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Per-subject PCA component activations over time.

    :param scores_3d: ``(S, T, n_pca)`` per-subject PCA scores.
    :param sfreq: Sampling frequency (Hz).
    """
    n_show = min(n_show, scores_3d.shape[2])
    n_subj = scores_3d.shape[0]
    time = np.arange(scores_3d.shape[1]) / sfreq

    fig, axes = plt.subplots(n_show, 1, figsize=(14, 2.5 * n_show), sharex=True)
    axes = _ensure_axes_iterable(axes)
    for i, ax in enumerate(axes):
        for s in range(n_subj):
            ax.plot(time, scores_3d[s, :, i], lw=0.5, alpha=0.6, label=f"S{s + 1}")
        ax.set_ylabel(f"PC {i + 1}")
    axes[-1].set_xlabel("Time (s)")
    axes[0].legend(fontsize=6, ncol=min(n_subj, 8), loc="upper right")
    fig.suptitle(f"Per-Subject Component Activations — {label}", fontsize=13)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_intersubject_pca_topomaps(
    channel_marginal: np.ndarray,
    info,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Optional[Figure]:
    """Topomaps of frequency-averaged PCA channel loadings.

    :param channel_marginal: ``(n_pca, C)`` mean loading across frequencies.
    :param info: MNE Info.
    """
    if info is None:
        _logger.warning("[%s] No MNE Info; skipping topomap.", label)
        return None

    import mne
    from mne.viz import plot_topomap

    eeg_info = mne.pick_info(info, mne.pick_types(info, eeg=True))
    n_show = min(n_show, channel_marginal.shape[0])

    fig, axes = plt.subplots(1, n_show, figsize=(3.5 * n_show, 4))
    axes = _ensure_axes_iterable(axes)
    last_im = None
    for i, ax in enumerate(axes):
        vals = channel_marginal[i]
        if vals.shape[0] < len(eeg_info["ch_names"]):
            topo_info = mne.pick_info(eeg_info, list(range(vals.shape[0])))
        else:
            topo_info = eeg_info
        vlim = np.percentile(np.abs(vals), 99)
        last_im, _ = plot_topomap(
            vals, topo_info, axes=ax, show=False, cmap="RdBu_r", vlim=(-vlim, vlim)
        )
        ax.set_title(f"PC {i + 1}")
    fig.suptitle(f"Component Topomaps (freq-averaged) — {label}", fontsize=12)
    if last_im is not None:
        fig.colorbar(last_im, ax=axes[-1], label="mean loading")
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_intersubject_similarity(
    scores_3d: np.ndarray,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Inter-subject similarity (S × S correlation) per PCA component.

    :param scores_3d: ``(S, T, n_pca)``.
    """
    n_show = min(n_show, scores_3d.shape[2])
    n_subj = scores_3d.shape[0]

    fig, axes = plt.subplots(
        1, n_show, figsize=(3.5 * n_show, 3.5), constrained_layout=True
    )
    axes = _ensure_axes_iterable(axes)
    last_im = None
    for i, ax in enumerate(axes):
        corr = np.corrcoef(scores_3d[:, :, i])
        last_im = ax.imshow(corr, cmap="RdBu_r", vmin=-1, vmax=1)
        ax.set_xticks(range(n_subj))
        ax.set_xticklabels([f"S{s + 1}" for s in range(n_subj)], fontsize=7)
        ax.set_yticks(range(n_subj))
        ax.set_yticklabels([f"S{s + 1}" for s in range(n_subj)], fontsize=7)
        ax.set_title(f"PC {i + 1}")
    if last_im is not None:
        fig.colorbar(last_im, ax=axes[-1], label="Pearson r")
    fig.suptitle(f"Inter-Subject Correlation per Component — {label}", fontsize=12)
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_intersubject_band_resolved_loadings(
    band_loadings: dict[str, np.ndarray],
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Grouped bar chart of band-resolved PCA component loadings.

    :param band_loadings: ``{band: (n_pca,)}`` mean |loading| per band per PC.
    """
    bands = list(band_loadings.keys())
    n_pca = len(next(iter(band_loadings.values())))
    n_show = min(n_show, n_pca)
    x = np.arange(n_show)
    width = 0.8 / len(bands)

    fig, ax = plt.subplots(figsize=(max(10, n_show), 5))
    for j, band in enumerate(bands):
        ax.bar(
            x + j * width,
            band_loadings[band][:n_show],
            width,
            label=band,
            color=_BAND_COLORS.get(band, "grey"),
            edgecolor="white",
        )
    ax.set_xticks(x + width * len(bands) / 2)
    ax.set_xticklabels([f"PC {i + 1}" for i in range(n_show)])
    ax.set_ylabel("Mean |loading|")
    ax.set_title(f"Band-Resolved Component Loadings — {label}")
    ax.legend()
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_intersubject_group_mean_activations(
    scores_3d: np.ndarray,
    sfreq: float,
    *,
    n_show: int = 4,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Group mean ± SD component activations over time.

    :param scores_3d: ``(S, T, n_pca)``.
    :param sfreq: Sampling frequency (Hz).
    """
    n_show = min(n_show, scores_3d.shape[2])
    time = np.arange(scores_3d.shape[1]) / sfreq
    mean = scores_3d.mean(axis=0)  # (T, K)
    std = scores_3d.std(axis=0)

    fig, axes = plt.subplots(n_show, 1, figsize=(14, 2.5 * n_show), sharex=True)
    axes = _ensure_axes_iterable(axes)
    for i, ax in enumerate(axes):
        ax.plot(time, mean[:, i], color="steelblue", lw=0.8, label="Mean")
        ax.fill_between(
            time,
            mean[:, i] - std[:, i],
            mean[:, i] + std[:, i],
            alpha=0.25,
            color="steelblue",
        )
        ax.set_ylabel(f"PC {i + 1}")
    axes[-1].set_xlabel("Time (s)")
    fig.suptitle(f"Group-Mean Component Activations — {label}", fontsize=13)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_intersubject_cross_component_correlation(
    pca_scores: np.ndarray,
    ica_sources: np.ndarray,
    *,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Cross-component correlation matrices (PCA + ICA)."""
    return plot_superbrain_cross_component_correlation(
        pca_scores, ica_sources, label=label, save_path=save_path
    )


def plot_intersubject_ica_channel_freq_maps(
    ica_mixing_3d: np.ndarray,
    freqs: np.ndarray,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """ICA spatial-spectral maps (channel × frequency heatmaps).

    :param ica_mixing_3d: ``(C, F, n_ica)`` ICA mixing reshaped.
    :param freqs: Morlet frequencies (Hz).
    """
    n_ica = ica_mixing_3d.shape[2]
    n_show = min(n_show, n_ica)
    n_cols = min(3, n_show)
    n_rows = int(np.ceil(n_show / n_cols))

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(5 * n_cols, 4 * n_rows))
    flat = np.array(axes).flatten() if n_show > 1 else [axes]
    for i in range(n_show):
        ax = flat[i]
        im = ax.imshow(
            ica_mixing_3d[:, :, i],
            aspect="auto",
            origin="lower",
            extent=[freqs[0], freqs[-1], 0, ica_mixing_3d.shape[0]],
            cmap="RdBu_r",
        )
        ax.set_xlabel("Frequency (Hz)")
        ax.set_ylabel("Channel index")
        ax.set_title(f"IC {i + 1}")
        fig.colorbar(im, ax=ax)
    for i in range(n_show, len(flat)):
        flat[i].set_visible(False)
    fig.suptitle(f"ICA Spatial-Spectral Maps — {label}", fontsize=13)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_intersubject_ica_topomap_mean(
    ica_ch_mean: np.ndarray,
    info,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Optional[Figure]:
    """Topomaps of mean ICA channel loading (inter-subject approach)."""
    return plot_superbrain_ica_topomap_mean(
        ica_ch_mean, info, n_show=n_show, label=label, save_path=save_path
    )


def plot_intersubject_ica_topomap_variance(
    ica_ch_var: np.ndarray,
    info,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Optional[Figure]:
    """Topomaps of ICA channel loading variance (inter-subject approach)."""
    return plot_superbrain_ica_topomap_variance(
        ica_ch_var, info, n_show=n_show, label=label, save_path=save_path
    )


def plot_intersubject_ica_interindividual_correlation(
    ica_scores_3d: np.ndarray,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Inter-individual correlation of ICA time courses per component.

    :param ica_scores_3d: ``(S, T, n_ica)``.
    """
    n_ica = ica_scores_3d.shape[2]
    n_show = min(n_show, n_ica)
    n_subj = ica_scores_3d.shape[0]

    fig, axes = plt.subplots(
        1, n_show, figsize=(3.5 * n_show, 3.5), constrained_layout=True
    )
    axes = _ensure_axes_iterable(axes)
    last_im = None
    for i, ax in enumerate(axes):
        corr = np.corrcoef(ica_scores_3d[:, :, i])
        last_im = ax.imshow(corr, cmap="RdBu_r", vmin=-1, vmax=1)
        ax.set_xticks(range(n_subj))
        ax.set_xticklabels([f"S{s + 1}" for s in range(n_subj)], fontsize=7)
        ax.set_yticks(range(n_subj))
        ax.set_yticklabels([f"S{s + 1}" for s in range(n_subj)], fontsize=7)
        ax.set_title(f"IC {i + 1}")
    if last_im is not None:
        fig.colorbar(last_im, ax=axes[-1], label="Pearson r")
    fig.suptitle(
        f"Inter-Individual IC Correlations (time courses) — {label}",
        fontsize=12,
    )
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


# ===================================================================
# Temporal plots (10)
# ===================================================================


def plot_temporal_pca_scree(
    explained_variance_ratio: np.ndarray,
    *,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """PCA scree plot for the temporal approach."""
    return plot_superbrain_pca_scree(
        explained_variance_ratio, label=label, save_path=save_path
    )


def plot_temporal_ica_freq_time_maps(
    ica_components_ft: np.ndarray,
    freqs: np.ndarray,
    sfreq: float,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """ICA frequency × time component maps.

    :param ica_components_ft: ``(n_ica, n_freqs, n_times)`` reshaped ICA components.
    :param freqs: Morlet frequencies (Hz).
    :param sfreq: Sampling frequency (Hz).
    """
    n_show = min(n_show, ica_components_ft.shape[0])
    n_times = ica_components_ft.shape[2]
    time = np.arange(n_times) / sfreq
    n_cols = min(3, n_show)
    n_rows = int(np.ceil(n_show / n_cols))

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(5 * n_cols, 4 * n_rows))
    flat = np.array(axes).flatten() if n_show > 1 else [axes]
    for i in range(n_show):
        ax = flat[i]
        comp = ica_components_ft[i]
        vlim = np.percentile(np.abs(comp), 99)
        im = ax.imshow(
            comp,
            aspect="auto",
            origin="lower",
            extent=[time[0], time[-1], freqs[0], freqs[-1]],
            cmap="RdBu_r",
            vmin=-vlim,
            vmax=vlim,
        )
        ax.set_xlabel("Time (s)")
        ax.set_ylabel("Frequency (Hz)")
        ax.set_title(f"IC {i + 1}")
        fig.colorbar(im, ax=ax)
    for i in range(n_show, len(flat)):
        flat[i].set_visible(False)
    fig.suptitle(f"ICA Frequency × Time Component Maps — {label}", fontsize=13)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_temporal_ica_topomap_mean(
    ica_channel_mean: np.ndarray,
    info,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Optional[Figure]:
    """Topomaps of mean ICA channel loading (temporal approach)."""
    return plot_superbrain_ica_topomap_mean(
        ica_channel_mean, info, n_show=n_show, label=label, save_path=save_path
    )


def plot_temporal_ica_topomap_variance(
    ica_channel_var: np.ndarray,
    info,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Optional[Figure]:
    """Topomaps of ICA channel loading variance (temporal approach)."""
    return plot_superbrain_ica_topomap_variance(
        ica_channel_var, info, n_show=n_show, label=label, save_path=save_path
    )


def plot_temporal_ica_per_subject_topomaps(
    ica_scores_3d: np.ndarray,
    info,
    *,
    n_show_comp: int = 3,
    label: str,
    save_path: Optional[Path] = None,
) -> Optional[Figure]:
    """Per-subject topomaps for top ICA components.

    :param ica_scores_3d: ``(S, C, n_ica)``.
    :param info: MNE Info.
    """
    if info is None:
        _logger.warning("[%s] No MNE Info; skipping topomap.", label)
        return None

    import mne
    from mne.viz import plot_topomap

    eeg_info = mne.pick_info(info, mne.pick_types(info, eeg=True))
    n_subj, n_ch, n_ica = ica_scores_3d.shape
    n_show_comp = min(n_show_comp, n_ica)

    fig, axes = plt.subplots(
        n_show_comp, n_subj, figsize=(3 * n_subj, 3.5 * n_show_comp), squeeze=False
    )

    for k in range(n_show_comp):
        for s in range(n_subj):
            ax = axes[k, s]
            vals = ica_scores_3d[s, :, k]
            if vals.shape[0] < len(eeg_info["ch_names"]):
                topo_info = mne.pick_info(eeg_info, list(range(vals.shape[0])))
            else:
                topo_info = eeg_info
            plot_topomap(vals, topo_info, axes=ax, show=False, cmap="RdBu_r")
            if k == 0:
                ax.set_title(f"S{s + 1}", fontsize=9)
        axes[k, 0].set_ylabel(f"IC {k + 1}", rotation=90, labelpad=40)
    fig.suptitle(f"Per-Subject ICA Channel Loadings — {label}", fontsize=13)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_temporal_ica_timecourses(
    ica_time_profiles: np.ndarray,
    sfreq: float,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """ICA time-marginalized temporal profiles.

    :param ica_time_profiles: ``(n_ica, n_times)`` freq-averaged time courses.
    :param sfreq: Sampling frequency (Hz).
    """
    n_show = min(n_show, ica_time_profiles.shape[0])
    time = np.arange(ica_time_profiles.shape[1]) / sfreq

    fig, axes = plt.subplots(n_show, 1, figsize=(14, 2.5 * n_show), sharex=True)
    axes = _ensure_axes_iterable(axes)
    for i, ax in enumerate(axes):
        ax.plot(time, ica_time_profiles[i], lw=0.8, color="darkorange")
        ax.axhline(0, ls="--", color="gray", lw=0.5)
        ax.set_ylabel(f"IC {i + 1}")
        ax.set_title(f"IC {i + 1} — temporal profile")
    axes[-1].set_xlabel("Time (s)")
    fig.suptitle(f"ICA Component Time Courses (freq-averaged) — {label}", fontsize=13)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_temporal_ica_spectral_profiles(
    ica_freq_profiles: np.ndarray,
    freqs: np.ndarray,
    *,
    bands: Optional[dict[str, tuple[float, float]]] = None,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """ICA time-marginalized spectral (frequency) profiles.

    :param ica_freq_profiles: ``(n_ica, n_freqs)`` time-averaged freq profiles.
    :param freqs: Morlet frequencies (Hz).
    """
    n_show = min(n_show, ica_freq_profiles.shape[0])

    fig, axes = plt.subplots(n_show, 1, figsize=(10, 2.5 * n_show), sharex=True)
    axes = _ensure_axes_iterable(axes)
    for i, ax in enumerate(axes):
        ax.plot(freqs, ica_freq_profiles[i], lw=1.5, color="darkorange")
        ax.set_ylabel("|weight|")
        ax.set_title(f"IC {i + 1}")
        if bands is not None:
            for band, (lo, hi) in bands.items():
                ax.axvspan(lo, hi, alpha=0.2, color=_BAND_COLORS.get(band, "grey"))
    axes[-1].set_xlabel("Frequency (Hz)")
    fig.suptitle(f"ICA Spectral Profiles (time-averaged) — {label}", fontsize=13)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_temporal_ica_intersubject_correlation(
    ica_scores_3d: np.ndarray,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Inter-subject correlation of ICA channel loadings (temporal approach).

    :param ica_scores_3d: ``(S, C, n_ica)``.
    """
    return plot_superbrain_ica_interindividual_correlation(
        ica_scores_3d, n_show=n_show, label=label, save_path=save_path
    )


def plot_temporal_ica_band_energy(
    band_energy: dict[str, np.ndarray],
    *,
    n_show: int = 10,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Band-resolved ICA component energy (grouped bar chart).

    :param band_energy: ``{band: (n_ica,)}`` mean squared weight per band per IC.
    """
    bands = list(band_energy.keys())
    n_ica = len(next(iter(band_energy.values())))
    n_show = min(n_show, n_ica)
    x = np.arange(n_show)
    width = 0.8 / len(bands)

    fig, ax = plt.subplots(figsize=(max(10, n_show), 5))
    for j, band in enumerate(bands):
        ax.bar(
            x + j * width,
            band_energy[band][:n_show],
            width,
            label=band,
            color=_BAND_COLORS.get(band, "grey"),
            edgecolor="white",
        )
    ax.set_xticks(x + width * len(bands) / 2)
    ax.set_xticklabels([f"IC {i + 1}" for i in range(n_show)])
    ax.set_ylabel("Mean squared weight")
    ax.set_title(f"Band-Resolved ICA Component Energy — {label}")
    ax.legend()
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_temporal_ica_component_correlation(
    ica_time_profiles: np.ndarray,
    *,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Correlation matrix of ICA temporal profiles.

    :param ica_time_profiles: ``(n_ica, n_times)``.
    """
    corr = np.corrcoef(ica_time_profiles)
    n = corr.shape[0]

    fig, ax = plt.subplots(figsize=(7, 6))
    im = ax.imshow(corr, cmap="RdBu_r", vmin=-1, vmax=1)
    ax.set_xticks(range(n))
    ax.set_xticklabels([f"IC {i + 1}" for i in range(n)], fontsize=8)
    ax.set_yticks(range(n))
    ax.set_yticklabels([f"IC {i + 1}" for i in range(n)], fontsize=8)
    ax.set_title(f"ICA Component Correlation Matrix — {label}")
    fig.colorbar(im, ax=ax, label="Pearson r")
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


# ===================================================================
# Inverted Super-Brain plots (10)
# ===================================================================


def plot_inverted_pca_scree(
    explained_variance_ratio: np.ndarray,
    *,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """PCA scree plot for the inverted super-brain approach."""
    return plot_superbrain_pca_scree(
        explained_variance_ratio, label=label, save_path=save_path
    )


def plot_inverted_ica_temporal_patterns(
    ica_components: np.ndarray,
    sfreq: float,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """ICA temporal component patterns (one row per IC).

    :param ica_components: ``(n_ica, T)`` ICA temporal patterns.
    :param sfreq: Sampling frequency (Hz).
    """
    n_show = min(n_show, ica_components.shape[0])
    time = np.arange(ica_components.shape[1]) / sfreq
    vlim = np.percentile(np.abs(ica_components[:n_show]), 99)

    fig, axes = plt.subplots(n_show, 1, figsize=(14, 2.5 * n_show), sharex=True)
    axes = _ensure_axes_iterable(axes)
    for i, ax in enumerate(axes):
        ax.plot(time, ica_components[i], lw=0.8, color="darkorange")
        ax.set_ylim(-vlim, vlim)
        ax.set_ylabel(f"IC {i + 1}")
        ax.set_title(f"ICA Temporal Pattern {i + 1}")
    axes[-1].set_xlabel("Time (s)")
    fig.suptitle(f"ICA Temporal Component Patterns — {label}", fontsize=13)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_inverted_ica_subject_loadings(
    subject_loadings: np.ndarray,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Horizontal bar chart of per-subject mean |score| (inverted approach).

    :param subject_loadings: ``(S, n_ica)`` mean |score| over channels and freqs.
    """
    n_show = min(n_show, subject_loadings.shape[1])
    n_subj = subject_loadings.shape[0]

    fig, axes = plt.subplots(1, n_show, figsize=(3 * n_show, 4), sharey=True)
    axes = _ensure_axes_iterable(axes)
    for i, ax in enumerate(axes):
        ax.barh(range(n_subj), subject_loadings[:, i], color="steelblue")
        ax.set_xlabel("|score|")
        ax.set_title(f"IC {i + 1}")
    axes[0].set_yticks(range(n_subj))
    axes[0].set_yticklabels([f"S{s + 1}" for s in range(n_subj)])
    axes[0].set_ylabel("Subject")
    fig.suptitle(f"Subject Loadings (ICA) — {label}", fontsize=13)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_inverted_ica_channel_topomap(
    channel_loadings: np.ndarray,
    info,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Optional[Figure]:
    """Topomaps of mean |score| ICA channel loadings (inverted approach).

    :param channel_loadings: ``(C, n_ica)`` mean |score| over S and F.
    :param info: MNE Info.
    """
    if info is None:
        _logger.warning("[%s] No MNE Info; skipping topomap.", label)
        return None

    import mne
    from mne.viz import plot_topomap

    eeg_info = mne.pick_info(info, mne.pick_types(info, eeg=True))
    n_show = min(n_show, channel_loadings.shape[1])

    fig, axes = plt.subplots(1, n_show, figsize=(3.5 * n_show, 4))
    axes = _ensure_axes_iterable(axes)
    last_im = None
    for i, ax in enumerate(axes):
        vals = channel_loadings[:, i]
        if vals.shape[0] < len(eeg_info["ch_names"]):
            topo_info = mne.pick_info(eeg_info, list(range(vals.shape[0])))
        else:
            topo_info = eeg_info
        vlim = np.percentile(vals, 99)
        last_im, _ = plot_topomap(
            vals, topo_info, axes=ax, show=False, cmap="RdBu_r", vlim=(0, vlim)
        )
        ax.set_title(f"IC {i + 1}")
    fig.suptitle(f"ICA Channel Loadings (mean |score|) — {label}", fontsize=12)
    if last_im is not None:
        fig.colorbar(last_im, ax=axes[-1], label="mean |score|")
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_inverted_ica_topomap_mean(
    ica_ch_mean: np.ndarray,
    info,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Optional[Figure]:
    """Topomaps of mean ICA channel loading (inverted approach)."""
    return plot_superbrain_ica_topomap_mean(
        ica_ch_mean, info, n_show=n_show, label=label, save_path=save_path
    )


def plot_inverted_ica_topomap_variance(
    ica_ch_var: np.ndarray,
    info,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Optional[Figure]:
    """Topomaps of ICA channel loading variance (inverted approach)."""
    return plot_superbrain_ica_topomap_variance(
        ica_ch_var, info, n_show=n_show, label=label, save_path=save_path
    )


def plot_inverted_ica_freq_loadings(
    freq_loadings: np.ndarray,
    freqs: np.ndarray,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Per-IC frequency loading curves (inverted approach).

    :param freq_loadings: ``(F, n_ica)`` mean |score| over S and C.
    :param freqs: Morlet frequencies (Hz).
    """
    n_show = min(n_show, freq_loadings.shape[1])

    fig, axes = plt.subplots(n_show, 1, figsize=(10, 2.5 * n_show), sharex=True)
    axes = _ensure_axes_iterable(axes)
    for i, ax in enumerate(axes):
        ax.plot(freqs, freq_loadings[:, i], color="darkorange", lw=1.5)
        vlim = np.percentile(freq_loadings[:, i], 99)
        ax.set_ylim(0, vlim)
        ax.set_ylabel("|score|")
        ax.set_title(f"IC {i + 1}")
    axes[-1].set_xlabel("Frequency (Hz)")
    fig.suptitle(f"Frequency Loadings (ICA) — {label}", fontsize=13)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_inverted_ica_spectrograms(
    ica_components: np.ndarray,
    sfreq: float,
    freqs_max: float,
    *,
    n_show: int = 4,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """STFT spectrograms of ICA temporal patterns (inverted approach).

    :param ica_components: ``(n_ica, T)`` ICA temporal patterns.
    :param sfreq: Sampling frequency (Hz).
    :param freqs_max: Maximum frequency to display (Hz).
    """
    from scipy.signal import spectrogram as sp_spectrogram

    n_show = min(n_show, ica_components.shape[0])
    nperseg = int(sfreq * 2)
    noverlap = int(sfreq)

    fig, axes = plt.subplots(n_show, 1, figsize=(14, 3 * n_show), sharex=True)
    axes = _ensure_axes_iterable(axes)
    for i, ax in enumerate(axes):
        f, t, Sxx = sp_spectrogram(
            ica_components[i], fs=sfreq, nperseg=nperseg, noverlap=noverlap
        )
        mask = f <= freqs_max
        Sxx_db = 10 * np.log10(Sxx[mask] + 1e-12)
        vmin, vmax = np.percentile(Sxx_db, [1, 99])
        ax.pcolormesh(
            t, f[mask], Sxx_db, cmap="inferno", shading="auto", vmin=vmin, vmax=vmax
        )
        ax.set_ylabel("Freq (Hz)")
        ax.set_title(f"IC {i + 1} spectrogram")
    axes[-1].set_xlabel("Time (s)")
    fig.suptitle(f"ICA Component Spectrograms — {label}", fontsize=13)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_inverted_ica_interindividual_correlation(
    ica_channel_loadings: np.ndarray,
    *,
    n_show: int = 6,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Inter-individual IC correlations (channel loadings, inverted approach).

    :param ica_channel_loadings: ``(S, C, n_ica)``.
    """
    return plot_superbrain_ica_interindividual_correlation(
        ica_channel_loadings, n_show=n_show, label=label, save_path=save_path
    )


def plot_inverted_cross_component_correlation(
    pca_scores: np.ndarray,
    ica_scores: np.ndarray,
    *,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Cross-component correlation (PCA + ICA, inverted approach)."""
    return plot_superbrain_cross_component_correlation(
        pca_scores, ica_scores, label=label, save_path=save_path
    )


# ===================================================================
# Cross-band comparison plots
# ===================================================================


def plot_cross_band_scree_comparison(
    band_variance: dict[str, np.ndarray],
    *,
    approach: str,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Overlay PCA scree curves across frequency bands for one approach.

    :param band_variance: ``{band: (n_pca,)}`` explained-variance ratios.
    :param approach: Human-readable approach name (e.g. ``"Super-Brain"``).
    """
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    for band, evr in band_variance.items():
        n = len(evr)
        color = _BAND_COLORS.get(band, "grey")
        axes[0].plot(range(1, n + 1), evr, "o-", label=band, color=color, ms=4)
        axes[1].plot(
            range(1, n + 1), np.cumsum(evr), "o-", label=band, color=color, ms=4
        )
    axes[0].set_xlabel("Component")
    axes[0].set_ylabel("Variance explained")
    axes[0].set_title(f"{approach} — Per-Band Scree — {label}")
    axes[0].legend(fontsize=8)
    axes[1].axhline(0.9, ls="--", color="gray", label="90 %")
    axes[1].set_xlabel("Number of components")
    axes[1].set_ylabel("Cumulative variance")
    axes[1].set_title(f"{approach} — Per-Band Cumulative Variance — {label}")
    axes[1].legend(fontsize=8)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_cross_band_variance_summary(
    band_variance: dict[str, dict[str, np.ndarray]],
    *,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Bar chart of total PCA variance captured (top-K) across bands × approaches.

    :param band_variance: ``{approach: {band: (n_pca,)}}`` explained-variance ratios.
    """
    approaches = list(band_variance.keys())
    all_bands: list[str] = []
    for inner in band_variance.values():
        for b in inner:
            if b not in all_bands:
                all_bands.append(b)

    n_approaches = len(approaches)
    x = np.arange(len(all_bands))
    width = 0.8 / max(n_approaches, 1)

    fig, ax = plt.subplots(figsize=(max(10, len(all_bands) * 2), 5))
    approach_colors = plt.cm.Set2(np.linspace(0, 1, n_approaches))  # noqa: N806
    for j, approach in enumerate(approaches):
        vals = []
        for band in all_bands:
            evr = band_variance[approach].get(band)
            vals.append(float(evr.sum()) if evr is not None else 0.0)
        ax.bar(x + j * width, vals, width, label=approach, color=approach_colors[j])
    ax.set_xticks(x + width * n_approaches / 2)
    ax.set_xticklabels(all_bands)
    ax.set_ylabel("Total PCA variance explained")
    ax.set_title(f"Cross-Band Variance Summary — {label}")
    ax.legend(fontsize=8)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig
