"""
Reusable visualisation functions for wavelet (power & phase) analysis.

These plots reproduce, in script form, the figures generated by the
exploratory notebooks under ``notebooks/03-wavelet-analysis/``.

Every function accepts pre-computed numpy arrays plus a small set of
display parameters and writes one figure to disk via ``save_path``.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from matplotlib.figure import Figure
from scipy.stats import circmean

from src.analysis.isc import FREQUENCY_BANDS

_logger = logging.getLogger(__name__)


_BAND_BG_COLORS: dict[str, str] = {
    "delta": "#d4e6f1",
    "theta": "#d5f5e3",
    "alpha": "#fdebd0",
    "beta": "#fadbd8",
    "gamma": "#e8daef",
}


def _save_fig(fig: Figure, save_path: Optional[Path]) -> None:
    if save_path is None:
        return
    save_path = Path(save_path)
    save_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(save_path, dpi=150, bbox_inches="tight")


def _ensure_axes_iterable(axes):
    """Return ``axes`` as a list, even when matplotlib returned a scalar."""
    if hasattr(axes, "__iter__"):
        return list(axes)
    return [axes]


# ---------------------------------------------------------------------------
# Power-domain plots
# ---------------------------------------------------------------------------


def plot_spectral_profile(
    bb_data: np.ndarray,
    freqs: np.ndarray,
    *,
    label: str,
    bands: Optional[dict[str, tuple[float, float]]] = None,
    save_path: Optional[Path] = None,
) -> Figure:
    """Grand-average wavelet power spectrum and channel × frequency image.

    :param bb_data: Wavelet power, shape ``(n_subjects, n_channels, n_freqs,
        n_times)``.
    :param freqs: Morlet frequencies (Hz), length ``n_freqs``.
    :param label: Dataset label used in plot titles.
    :param bands: Optional band definitions for shaded background regions.
    :param save_path: Where to write the figure.
    :return: The created figure.
    """
    if bb_data.ndim != 4:
        raise ValueError(
            f"bb_data must be 4D (subjects, channels, freqs, times), "
            f"got shape {bb_data.shape}"
        )
    bands = bands if bands is not None else FREQUENCY_BANDS
    n_channels = bb_data.shape[1]

    grand_avg_ch_freq = bb_data.mean(axis=(0, 3))  # (n_channels, n_freqs)
    grand_avg_spectrum = grand_avg_ch_freq.mean(axis=0)  # (n_freqs,)

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    axes[0].plot(freqs, grand_avg_spectrum, color="steelblue", linewidth=1.5)
    axes[0].set_xlabel("Frequency (Hz)")
    axes[0].set_ylabel("Mean wavelet power")
    axes[0].set_title(f"Grand-average spectrum — {label}")
    for band, (lo, hi) in bands.items():
        axes[0].axvspan(
            lo, hi, alpha=0.25, color=_BAND_BG_COLORS.get(band, "grey"), label=band
        )
    axes[0].legend(fontsize=8, loc="upper right")

    im = axes[1].imshow(
        grand_avg_ch_freq,
        aspect="auto",
        origin="lower",
        extent=[freqs[0], freqs[-1], 0, n_channels],
        cmap="viridis",
    )
    axes[1].set_xlabel("Frequency (Hz)")
    axes[1].set_ylabel("Channel index")
    axes[1].set_title(f"Channel × frequency power — {label}")
    fig.colorbar(im, ax=axes[1], label="Power")

    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_tf_map(
    bb_data: np.ndarray,
    freqs: np.ndarray,
    sfreq: float,
    *,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Channel- and subject-averaged time–frequency map of wavelet power.

    :param bb_data: ``(n_subjects, n_channels, n_freqs, n_times)`` wavelet
        power.
    :param freqs: Morlet frequencies (Hz).
    :param sfreq: Sampling frequency for the time axis.
    """
    if bb_data.ndim != 4:
        raise ValueError(
            f"bb_data must be 4D (subjects, channels, freqs, times), "
            f"got shape {bb_data.shape}"
        )
    tfr_map = bb_data.mean(axis=(0, 1))  # (n_freqs, n_times)
    n_times = bb_data.shape[3]
    time = np.arange(n_times) / float(sfreq)

    fig, ax = plt.subplots(figsize=(14, 5))
    im = ax.imshow(
        tfr_map,
        aspect="auto",
        origin="lower",
        extent=[time[0], time[-1], freqs[0], freqs[-1]],
        cmap="inferno",
    )
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Frequency (Hz)")
    ax.set_title(f"Time–frequency map (mean wavelet power) — {label}")
    fig.colorbar(im, ax=ax, label="Power")

    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_band_power_timecourse(
    bb_data: np.ndarray,
    freqs: np.ndarray,
    sfreq: float,
    *,
    label: str,
    bands: Optional[dict[str, tuple[float, float]]] = None,
    percentile_clip: float = 99.0,
    save_path: Optional[Path] = None,
) -> Figure:
    """Per-band z-scored mean ± SD power time course (one panel per band)."""
    if bb_data.ndim != 4:
        raise ValueError(
            f"bb_data must be 4D (subjects, channels, freqs, times), "
            f"got shape {bb_data.shape}"
        )
    bands = bands if bands is not None else FREQUENCY_BANDS
    n_times = bb_data.shape[3]
    time = np.arange(n_times) / float(sfreq)

    fig, axes = plt.subplots(len(bands), 1, figsize=(14, 3 * len(bands)), sharex=True)
    axes = _ensure_axes_iterable(axes)

    for ax, (band, (lo, hi)) in zip(axes, bands.items()):
        band_mask = (freqs >= lo) & (freqs <= hi)
        if not band_mask.any():
            ax.set_visible(False)
            continue
        band_power = bb_data[:, :, band_mask, :].mean(axis=2)
        bp_mean = band_power.mean(axis=2, keepdims=True)
        bp_std = band_power.std(axis=2, keepdims=True)
        band_power_z = (band_power - bp_mean) / (bp_std + 1e-10)
        band_ch_avg = band_power_z.mean(axis=1)
        group_mean = band_ch_avg.mean(axis=0)
        group_std = band_ch_avg.std(axis=0)

        upper = np.percentile(group_mean + group_std, percentile_clip)
        lower = np.percentile(group_mean - group_std, 100 - percentile_clip)

        ax.plot(time, group_mean, color="steelblue", linewidth=0.8, label="Mean")
        ax.fill_between(
            time,
            group_mean - group_std,
            group_mean + group_std,
            alpha=0.25,
            color="steelblue",
            label="±1 SD",
        )
        ax.set_ylim(lower, upper)
        ax.set_ylabel("Z-scored power")
        ax.set_title(f"{band} ({lo:.0f}–{hi:.0f} Hz)")
        ax.legend(fontsize=7, loc="upper right")

    axes[-1].set_xlabel("Time (s)")
    fig.suptitle(
        f"Per-band wavelet power time course (z-scored) — {label}",
        fontsize=13,
        y=1.01,
    )
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_intersubject_variance(
    bb_data: np.ndarray,
    freqs: np.ndarray,
    sfreq: float,
    *,
    label: str,
    bands: Optional[dict[str, tuple[float, float]]] = None,
    percentile_clip: float = 99.0,
    save_path: Optional[Path] = None,
) -> Figure:
    """Per-band intersubject variance (z-scored) traces.

    Companion to ``plot_band_power_timecourse`` — low variance ↔ high
    inter-subject synchrony.
    """
    if bb_data.ndim != 4:
        raise ValueError(
            f"bb_data must be 4D (subjects, channels, freqs, times), "
            f"got shape {bb_data.shape}"
        )
    bands = bands if bands is not None else FREQUENCY_BANDS
    n_times = bb_data.shape[3]
    time = np.arange(n_times) / float(sfreq)

    fig, axes = plt.subplots(len(bands), 1, figsize=(14, 3 * len(bands)), sharex=True)
    axes = _ensure_axes_iterable(axes)

    for ax, (band, (lo, hi)) in zip(axes, bands.items()):
        band_mask = (freqs >= lo) & (freqs <= hi)
        if not band_mask.any():
            ax.set_visible(False)
            continue
        band_power_3d = bb_data[:, :, band_mask, :].mean(axis=2)
        bp_mean = band_power_3d.mean(axis=2, keepdims=True)
        bp_std = band_power_3d.std(axis=2, keepdims=True)
        band_power_z = (band_power_3d - bp_mean) / (bp_std + 1e-10)
        var_t = band_power_z.var(axis=0).mean(axis=0)  # (n_times,)

        upper = np.percentile(var_t, percentile_clip)
        ax.plot(time, var_t, color="coral", linewidth=0.8)
        ax.set_ylim(bottom=0, top=upper)
        ax.set_ylabel("Variance")
        ax.set_title(
            f"{band} ({lo:.0f}–{hi:.0f} Hz) — intersubject variance (z-scored)"
        )

    axes[-1].set_xlabel("Time (s)")
    fig.suptitle(
        f"Wavelet-domain intersubject variance (z-scored) — {label}",
        fontsize=13,
        y=1.01,
    )
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_wavelet_loo_isc_bar(
    band_mean_iscs: dict[str, np.ndarray],
    *,
    label: str,
    save_path: Optional[Path] = None,
    color: str = "steelblue",
) -> Figure:
    """Bar chart (mean / median) of per-band wavelet LOO-ISC.

    :param band_mean_iscs: ``{band: (n_channels,)}`` channel-wise mean LOO-ISC
        from wavelet-transformed data.
    """
    bands_list = list(band_mean_iscs.keys())
    means = [band_mean_iscs[b].mean() for b in bands_list]
    medians = [np.median(band_mean_iscs[b]) for b in bands_list]

    fig, ax = plt.subplots(figsize=(8, 5))
    x = np.arange(len(bands_list))
    width = 0.35
    ax.bar(x - width / 2, means, width, label="Mean", color=color)
    ax.bar(x + width / 2, medians, width, label="Median", color="coral")
    ax.set_xticks(x)
    ax.set_xticklabels(bands_list)
    ax.set_ylabel("LOO-ISC (channel average)")
    ax.set_title(f"Per-band wavelet LOO-ISC — {label}")
    ax.legend()
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_wavelet_loo_isc_distributions(
    band_mean_iscs: dict[str, np.ndarray],
    *,
    label: str,
    save_path: Optional[Path] = None,
    color: str = "steelblue",
) -> Figure:
    """Per-band histograms of channel-wise LOO-ISC."""
    bands_list = list(band_mean_iscs.keys())
    fig, axes = plt.subplots(
        1, len(bands_list), figsize=(3.5 * len(bands_list), 4), sharey=True
    )
    axes = _ensure_axes_iterable(axes)

    for ax, band in zip(axes, bands_list):
        vals = band_mean_iscs[band]
        clip = np.percentile(vals, 99)
        ax.hist(vals[vals <= clip], bins=30, color=color, edgecolor="white", alpha=0.8)
        ax.axvline(
            vals.mean(),
            color="red",
            linestyle="--",
            linewidth=1,
            label=f"mean={vals.mean():.3f}",
        )
        ax.set_xlabel("LOO-ISC")
        ax.set_title(band)
        ax.legend(fontsize=7)

    axes[0].set_ylabel("Number of channels")
    fig.suptitle(f"Wavelet LOO-ISC distributions — {label}", fontsize=13, y=1.02)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_wavelet_topomap_isc(
    band_mean_iscs: dict[str, np.ndarray],
    info,
    *,
    label: str,
    title_prefix: str = "Topographic LOO-ISC per band",
    save_path: Optional[Path] = None,
) -> Optional[Figure]:
    """One scalp topomap per band coloured by mean channel LOO-ISC.

    Returns ``None`` if MNE info is unavailable. The first dimension of each
    band's ``(n_channels,)`` array must match the number of EEG channels in
    ``info``.
    """
    if info is None:
        _logger.warning(
            "[%s] No MNE Info object available; skipping topomap plot.", label
        )
        return None

    import mne
    from mne.viz import plot_topomap

    eeg_info = mne.pick_info(info, mne.pick_types(info, eeg=True))

    bands_list = list(band_mean_iscs.keys())
    n_bands = len(bands_list)
    fig, axes = plt.subplots(1, n_bands, figsize=(3.5 * n_bands, 4))
    axes = _ensure_axes_iterable(axes)

    last_im = None
    for ax, band in zip(axes, bands_list):
        isc_values = band_mean_iscs[band]
        if isc_values.shape[0] < len(eeg_info["ch_names"]):
            band_info = mne.pick_info(eeg_info, list(range(isc_values.shape[0])))
        else:
            band_info = eeg_info
        last_im, _ = plot_topomap(
            isc_values, band_info, axes=ax, show=False, cmap="RdBu_r"
        )
        ax.set_title(band, fontsize=10)

    fig.suptitle(f"{title_prefix} — {label}", fontsize=12)
    if last_im is not None:
        fig.colorbar(last_im, ax=axes[-1], label="mean LOO-ISC")
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_tf_isc(
    bb_data: np.ndarray,
    freqs: np.ndarray,
    *,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Channel-averaged LOO-ISC as a function of frequency.

    :param bb_data: ``(n_subjects, n_channels, n_freqs, n_times)`` wavelet
        power.
    """
    from src.analysis.isc import compute_loo_isc

    if bb_data.ndim != 4:
        raise ValueError(
            f"bb_data must be 4D (subjects, channels, freqs, times), "
            f"got shape {bb_data.shape}"
        )

    n_subjects, n_channels, n_freqs, n_times = bb_data.shape
    bb_flat = bb_data.reshape(n_subjects, n_channels * n_freqs, n_times)
    _, tf_isc_flat = compute_loo_isc(bb_flat)
    tf_isc_ch_freq = tf_isc_flat.reshape(n_channels, n_freqs)
    tf_isc_freq = tf_isc_ch_freq.mean(axis=0)

    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(freqs, tf_isc_freq, color="steelblue", lw=2)
    ax.axhline(0, color="gray", lw=0.8, ls="--")
    ax.set_xlabel("Frequency (Hz)")
    ax.set_ylabel("Mean LOO-ISC (channel-averaged)")
    ax.set_title(f"LOO-ISC vs. Frequency — {label}")
    sns.despine()
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_cross_frequency_coupling(
    bb_data: np.ndarray,
    freqs: np.ndarray,
    *,
    label: str,
    bands: Optional[dict[str, tuple[float, float]]] = None,
    save_path: Optional[Path] = None,
) -> Figure:
    """Pearson correlation matrix between band-averaged power time courses.

    :param bb_data: ``(n_subjects, n_channels, n_freqs, n_times)``.
    """
    if bb_data.ndim != 4:
        raise ValueError(
            f"bb_data must be 4D (subjects, channels, freqs, times), "
            f"got shape {bb_data.shape}"
        )
    bands = bands if bands is not None else FREQUENCY_BANDS

    band_power_tc: dict[str, np.ndarray] = {}
    for band, (lo, hi) in bands.items():
        band_mask = (freqs >= lo) & (freqs <= hi)
        if not band_mask.any():
            continue
        band_power_tc[band] = bb_data[:, :, band_mask, :].mean(axis=(0, 1, 2))

    valid_bands = list(band_power_tc.keys())
    n_valid = len(valid_bands)
    cfc_matrix = np.full((n_valid, n_valid), np.nan)
    for i, b1 in enumerate(valid_bands):
        for j, b2 in enumerate(valid_bands):
            cfc_matrix[i, j] = np.corrcoef(band_power_tc[b1], band_power_tc[b2])[0, 1]

    fig, ax = plt.subplots(figsize=(6, 5))
    im = ax.imshow(cfc_matrix, vmin=-1, vmax=1, cmap="RdBu_r")
    ax.set_xticks(range(n_valid))
    ax.set_yticks(range(n_valid))
    ax.set_xticklabels(valid_bands, rotation=45)
    ax.set_yticklabels(valid_bands)
    ax.set_title(f"Cross-Band Power Correlation — {label}")
    fig.colorbar(im, ax=ax, label="Pearson r")
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_power_phase_joint(
    power_band_iscs: dict[str, np.ndarray],
    phase_band_iscs: dict[str, np.ndarray],
    *,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Grouped bar chart comparing power LOO-ISC vs. phase LOO-ISC per band."""
    common_bands = [b for b in power_band_iscs if b in phase_band_iscs]
    if not common_bands:
        raise ValueError("No bands present in both power and phase ISC dicts.")
    power_means = [power_band_iscs[b].mean() for b in common_bands]
    phase_means = [phase_band_iscs[b].mean() for b in common_bands]

    x = np.arange(len(common_bands))
    width = 0.35

    fig, ax = plt.subplots(figsize=(8, 4))
    ax.bar(x - width / 2, power_means, width, label="Power ISC", color="steelblue")
    ax.bar(x + width / 2, phase_means, width, label="Phase ISC (cos φ)", color="tomato")
    ax.set_xticks(x)
    ax.set_xticklabels(common_bands)
    ax.set_ylabel("Mean LOO-ISC")
    ax.set_title(f"Power vs. Phase ISC per Band — {label}")
    ax.legend()
    sns.despine()
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


# ---------------------------------------------------------------------------
# Phase-domain plots
# ---------------------------------------------------------------------------


def compute_itpc(phase_4d: np.ndarray) -> np.ndarray:
    """Inter-trial phase coherence over the subject axis.

    :param phase_4d: ``(n_subjects, n_channels, n_freqs, n_times)`` of wavelet
        phase angles in radians.
    :return: ``(n_channels, n_freqs, n_times)`` ITPC values in ``[0, 1]``.
    """
    if phase_4d.ndim != 4:
        raise ValueError(
            f"phase_4d must be 4D (subjects, channels, freqs, times), "
            f"got shape {phase_4d.shape}"
        )
    return np.abs(np.exp(1j * phase_4d).mean(axis=0))


def plot_phase_distribution(
    phase_4d: np.ndarray,
    *,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Linear and polar histograms of all wavelet phase values."""
    if phase_4d.ndim != 4:
        raise ValueError(
            f"phase_4d must be 4D (subjects, channels, freqs, times), "
            f"got shape {phase_4d.shape}"
        )
    all_phases = phase_4d.ravel()

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    axes[0].hist(
        all_phases,
        bins=64,
        density=True,
        color="steelblue",
        edgecolor="white",
        alpha=0.8,
    )
    axes[0].axhline(
        1.0 / (2 * np.pi), color="red", linestyle="--", label="Uniform density"
    )
    axes[0].set_xlabel("Phase (rad)")
    axes[0].set_ylabel("Density")
    axes[0].set_title(f"Phase distribution — {label}")
    axes[0].legend()

    ax_polar = fig.add_subplot(122, projection="polar")
    counts, bin_edges = np.histogram(all_phases, bins=64, range=(-np.pi, np.pi))
    centres = 0.5 * (bin_edges[:-1] + bin_edges[1:])
    widths = np.diff(bin_edges)
    ax_polar.bar(
        centres, counts, width=widths, color="steelblue", alpha=0.7, edgecolor="white"
    )
    ax_polar.set_title(f"Polar phase histogram — {label}", pad=15)
    axes[1].set_visible(False)

    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_itpc_spectrum(
    itpc_full: np.ndarray,
    freqs: np.ndarray,
    *,
    label: str,
    bands: Optional[dict[str, tuple[float, float]]] = None,
    save_path: Optional[Path] = None,
) -> Figure:
    """ITPC spectrum (time-averaged) and channel × frequency ITPC image."""
    if itpc_full.ndim != 3:
        raise ValueError(
            f"itpc_full must be 3D (channels, freqs, times), got shape {itpc_full.shape}"
        )
    bands = bands if bands is not None else FREQUENCY_BANDS
    n_channels = itpc_full.shape[0]

    itpc_ch_freq = itpc_full.mean(axis=2)
    itpc_spectrum = itpc_ch_freq.mean(axis=0)

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    axes[0].plot(freqs, itpc_spectrum, color="darkgreen", linewidth=1.5)
    axes[0].set_xlabel("Frequency (Hz)")
    axes[0].set_ylabel("Mean ITPC")
    axes[0].set_title(f"ITPC spectrum (time-averaged) — {label}")
    for band, (lo, hi) in bands.items():
        axes[0].axvspan(
            lo, hi, alpha=0.25, color=_BAND_BG_COLORS.get(band, "grey"), label=band
        )
    axes[0].legend(fontsize=8, loc="upper right")

    im = axes[1].imshow(
        itpc_ch_freq,
        aspect="auto",
        origin="lower",
        extent=[freqs[0], freqs[-1], 0, n_channels],
        cmap="YlGn",
        vmin=0,
    )
    axes[1].set_xlabel("Frequency (Hz)")
    axes[1].set_ylabel("Channel index")
    axes[1].set_title(f"Channel × frequency ITPC — {label}")
    fig.colorbar(im, ax=axes[1], label="ITPC")

    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_tf_itpc_map(
    itpc_full: np.ndarray,
    freqs: np.ndarray,
    sfreq: float,
    *,
    label: str,
    save_path: Optional[Path] = None,
) -> Figure:
    """Channel-averaged time–frequency ITPC heatmap."""
    if itpc_full.ndim != 3:
        raise ValueError(
            f"itpc_full must be 3D (channels, freqs, times), got shape {itpc_full.shape}"
        )
    itpc_tf = itpc_full.mean(axis=0)
    n_times = itpc_full.shape[2]
    time = np.arange(n_times) / float(sfreq)

    fig, ax = plt.subplots(figsize=(14, 5))
    im = ax.imshow(
        itpc_tf,
        aspect="auto",
        origin="lower",
        extent=[time[0], time[-1], freqs[0], freqs[-1]],
        cmap="YlGn",
        vmin=0,
    )
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Frequency (Hz)")
    ax.set_title(f"Time–frequency ITPC map — {label}")
    fig.colorbar(im, ax=ax, label="ITPC")

    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def plot_band_itpc_timecourse(
    itpc_full: np.ndarray,
    freqs: np.ndarray,
    sfreq: float,
    *,
    label: str,
    bands: Optional[dict[str, tuple[float, float]]] = None,
    save_path: Optional[Path] = None,
) -> Figure:
    """Per-band ITPC time course (one panel per band)."""
    if itpc_full.ndim != 3:
        raise ValueError(
            f"itpc_full must be 3D (channels, freqs, times), got shape {itpc_full.shape}"
        )
    bands = bands if bands is not None else FREQUENCY_BANDS
    n_times = itpc_full.shape[2]
    time = np.arange(n_times) / float(sfreq)

    fig, axes = plt.subplots(len(bands), 1, figsize=(14, 3 * len(bands)), sharex=True)
    axes = _ensure_axes_iterable(axes)

    for ax, (band, (lo, hi)) in zip(axes, bands.items()):
        band_mask = (freqs >= lo) & (freqs <= hi)
        if not band_mask.any():
            ax.set_visible(False)
            continue
        band_itpc = itpc_full[:, band_mask, :].mean(axis=1)  # (n_channels, n_times)
        band_itpc_avg = band_itpc.mean(axis=0)
        ax.plot(time, band_itpc_avg, color="darkgreen", linewidth=0.8)
        ax.set_ylabel("ITPC")
        ax.set_title(f"{band} ({lo:.0f}–{hi:.0f} Hz)")
        ax.set_ylim(bottom=0)

    axes[-1].set_xlabel("Time (s)")
    fig.suptitle(f"Per-band ITPC time course — {label}", fontsize=13, y=1.01)
    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig


def compute_phase_band_loo_iscs(
    phase_4d: np.ndarray,
    freqs: np.ndarray,
    bands: Optional[dict[str, tuple[float, float]]] = None,
) -> dict[str, np.ndarray]:
    """Per-band channel-wise LOO-ISC computed on cos(circmean(phase)).

    :param phase_4d: ``(n_subjects, n_channels, n_freqs, n_times)`` phase
        angles in radians.
    :param freqs: Wavelet frequencies (Hz).
    :return: ``{band: mean_loo_isc}`` shape ``(n_channels,)`` per band.
    """
    from src.analysis.isc import compute_loo_isc

    if phase_4d.ndim != 4:
        raise ValueError(
            f"phase_4d must be 4D (subjects, channels, freqs, times), "
            f"got shape {phase_4d.shape}"
        )
    bands = bands if bands is not None else FREQUENCY_BANDS

    out: dict[str, np.ndarray] = {}
    for band, (lo, hi) in bands.items():
        band_mask = (freqs >= lo) & (freqs <= hi)
        if not band_mask.any():
            continue
        band_phase_3d = circmean(
            phase_4d[:, :, band_mask, :], high=np.pi, low=-np.pi, axis=2
        )
        cos_phase_3d = np.cos(band_phase_3d)
        _, mean_loo_isc = compute_loo_isc(cos_phase_3d)
        out[band] = mean_loo_isc
    return out


def plot_itpc_vs_isc(
    itpc_full: np.ndarray,
    band_mean_iscs: dict[str, np.ndarray],
    freqs: np.ndarray,
    *,
    label: str,
    bands: Optional[dict[str, tuple[float, float]]] = None,
    save_path: Optional[Path] = None,
) -> Figure:
    """Side-by-side bar + scatter comparison of ITPC and phase LOO-ISC."""
    if itpc_full.ndim != 3:
        raise ValueError(
            f"itpc_full must be 3D (channels, freqs, times), got shape {itpc_full.shape}"
        )
    bands = bands if bands is not None else FREQUENCY_BANDS

    band_mean_itpc: dict[str, float] = {}
    for band, (lo, hi) in bands.items():
        band_mask = (freqs >= lo) & (freqs <= hi)
        if not band_mask.any():
            continue
        band_mean_itpc[band] = float(itpc_full[:, band_mask, :].mean())

    common = [b for b in bands if b in band_mean_itpc and b in band_mean_iscs]
    itpc_vals = [band_mean_itpc[b] for b in common]
    isc_vals = [band_mean_iscs[b].mean() for b in common]

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    x = np.arange(len(common))
    width = 0.35
    axes[0].bar(x - width / 2, itpc_vals, width, label="ITPC", color="darkgreen")
    axes[0].bar(x + width / 2, isc_vals, width, label="ISC(cos φ)", color="steelblue")
    axes[0].set_xticks(x)
    axes[0].set_xticklabels(common)
    axes[0].set_ylabel("Score")
    axes[0].set_title(f"ITPC vs Phase-ISC — {label}")
    axes[0].legend()

    axes[1].scatter(itpc_vals, isc_vals, s=80, color="purple", zorder=3)
    for i, band in enumerate(common):
        axes[1].annotate(
            band, (itpc_vals[i], isc_vals[i]), fontsize=9, ha="left", va="bottom"
        )
    axes[1].set_xlabel("Mean ITPC")
    axes[1].set_ylabel("Mean LOO-ISC(cos φ)")
    axes[1].set_title(f"ITPC–ISC relationship — {label}")

    fig.tight_layout()
    _save_fig(fig, save_path)
    plt.close(fig)
    return fig
