#!/bin/bash
#PBS -N PSILO_ISC
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=4:mem=60gb:scratch_local=60gb

#PBS -m ae
#PBS -j oe

set -e

# Ensure clean_scratch runs on exit, even on error
cleanup() {
echo "Running clean_scratch at $(date)"
clean_scratch
}
trap cleanup EXIT

echo "Task started at $(date)"

PROJECT_NAME="psilocybin-eeg"
SERVER_LOCATION="praha1"
DATADIR="/storage/$SERVER_LOCATION/home/$USER/$PROJECT_NAME"
SIF_IMAGE="/storage/$SERVER_LOCATION/home/$USER/singularity-images/psilo_music.sif"

export TMPDIR=$SCRATCHDIR

test -n "$SCRATCHDIR" || {
echo >&2 "SCRATCHDIR is not set!"
exit 1
}

cd "$DATADIR" || {
echo >&2 "Failed to enter DATADIR"
exit 1
}

cd "$SCRATCHDIR"

# Create the runner script for inside container
cat << 'EOF' > run_inside.sh
#!/bin/bash
source /opt/myproject/.venv/bin/activate
python /mnt/scripts/run_isc.py \
--experiment psilo_music \
--condition Placebo \
--window_fine_sec 1.0 \
--window_sec 5.0 \
--window_large_sec 15.0 \
--step_sec 2.5 \
--n_ch_subsample 64 \
--n_jobs -1
# --music_type CLASSIC PSYTRANCE \
EOF

chmod +x run_inside.sh

echo "Running inside Singularity at $(date)"

# Bind your project directory as /mnt inside container
singularity exec --nv -B "$DATADIR":/mnt "$SIF_IMAGE" bash run_inside.sh || {
    echo >&2 "Python script failed"
    exit 1
}

echo "Task finished at $(date)"

clean_scratch
